### ISSUE TITLE
NodeWidgetBaseComponent type missing

### ISSUE THREAD

**Issue by EugeneDelage** [zHaytam/Blazor.Diagrams#22]
Hi,
Trying to make a custom node, followed the instructions.
I created a class 
```
 public class CaptionNode : NodeModel
        {
            public CaptionNode(Point position = null) : base(position) { }

            public string Caption { get; set; }
        }
```
But on the Razor component, @inherits NodeWidgetBaseComponent<CaptionNode> NodeWidgetBaseComponent is not dounf. And I do have the Z.blazor in the dependencies...

Thanks

**Comment by zHaytam** [comment]
Hello,

Did you add `@using Blazor.Diagrams.Components.Base;` to your `_Imports.razor` file? Otherwise you'll have to provide the full type name, which is `Blazor.Diagrams.Components.Base.NodeWidgetBaseComponent `.

Hope this helps!

**Comment by EugeneDelage** [comment]
Hello,
I only had `@using Blazor.Diagrams.Components` in _imports.razor. So it does work now.

Thank you for the quick response
