### ISSUE TITLE
Update to .NET 5.0 preview ? 

### ISSUE THREAD

**Issue by andean00** [zHaytam/Blazor.Diagrams#26]
Hi guys, 
Great work wth this library !  Thanks so much. I tried the sample project and it works out of the box of course.
Unfortunately, my Blazorwasm project is already upgraded to the latest preview of .NET 5.0 before the release in a couple of months. 
Is there a way you guys could upgrade it in nuget ?  I did it locally in my machine and it works, and it took me 10 mins max:
 
Renamed every .netStandard* occurence in every project (.csproj) in the demo to  <TargetFramework>net5.0</TargetFramework>
Then I targeted  Version="5.0.0-rc.1.20451.17"   instead of 3.1

The demo works without issues in VS 2019 Version 16.8.0 Preview 3.1

But from my project, if I add the nuget package with Manage nuget packages, I get the current 3.1 version, so I cannot use it because I do not target netStandard at all. 

Is there a way I could use the compiled DLL directly in the meanwhile ?   I never do this, I always use Nuget, but is there a way I could make it work locally while the upgrade is performed in Nuget ?

Thank you so much in advance and cheers ! 

Javier

**Comment by zHaytam** [comment]
Hello!

I do plan to upgrade the library to use .NET 5 and especially CSS/JS Isolation, but I think it's better to wait for the official release, or maybe provide a preview package that users can choose to install.

In the meantime, you could:

1. Compile the project with .NET 5 like you did
2. Install it locally using something like `nuget add Z.Blazor.Diagrams.4.0.0.nupkg -source d:\source\nuget_repo` (of course you can change the directory of your local packages)
3. Go to VS and configure a new NuGet feed that points to that folder
4. Choose the new NuGet feed and Install the new version that you compiled

I hope this helps you!

**Comment by andean00** [comment]
Hi Haytam, 

Thank you a lot for the quick and detailed answer ! I agree with you to wait for the release. 
So far I have done the update on my existing project as the previews are released by MS and they are stable. 
Besides a hardcoded tcp port (!!) that I had to manually kill that was released in the last preview, there are no other issues and it is pretty stable 

I will try the technique you mention.
Thanks a lot and have a good weekend ! 

Javier

**Comment by andean00** [comment]
Just in case.... and if it can help anyone, for people playing with the last preview (5.0.0-rc.1.20451.14) I had to do this in the csproj:

<PropertyGroup>
    <PreBuildEvent>kill-port 9300</PreBuildEvent>
  </PropertyGroup>

That is the hardcoded port that MS released. 
Happy coding ! 

Javier

**Comment by zHaytam** [comment]
Oh god, totally forgot about this...
I am currently using this library in a Blazor WASM project that uses .NET 5, so I believe you don't even need to build anything, just reference the library in your project.
