### ISSUE TITLE
how to make Groups

### ISSUE THREAD

**Issue by mRmEEeZ** [zHaytam/Blazor.Diagrams#38]
Hello again

i have this idea of grouping nodes together
and this group contains nodes than can't be dragged outside of the group in such a way that the group boundaries (rounded rectangle) expands to contains it's nodes
this group of nodes has background color and label that can be placed:
top-left , top-right, top-center , bottom-center, bottom-left or bottom-right

**Comment by zHaytam** [comment]
Hi,

This is a tough one!
Currently, there is no out-of-the-box solution for this in the library, because it's a very advanced feature.

However, if you feel adventurous, you can do this using a custom node that acts like a group, and then replacing `DragNodeSubManager` with your own, which controls where nodes can move etc..

**Comment by mRmEEeZ** [comment]
any example of how achieving that ?

**Comment by zHaytam** [comment]
Unfortunately no, I'm currently trying some things out to see if I can make it better/easier!

**Comment by zHaytam** [comment]
Currently trying a possible solution:  
![](https://i.imgur.com/C8MuYn4.gif)

There are still a couple of problems I need to fix before this becomes a viable solution, but it looks promising!

**Comment by mRmEEeZ** [comment]
Fantastic !!
this looks very good , a bit of touch that would make it looks better is ability to give it rounded corners and coloring option
keep up the good work :)

**Comment by zHaytam** [comment]
After a lot of thinking and work, I finally finalized the initial rework of groups! 
They are now actual groups (containers) that are customizable (just likes nodes) and open up a lot of things for the future!  

Current limitations:

- No nested groups.
- No ports on groups.
- Some issues with the order of the links

That's the next step for groups!

![](https://i.imgur.com/TNo3WDe.png)
