### ISSUE TITLE
is it possible to resize the nodes?

### ISSUE THREAD

**Issue by carlosast** [zHaytam/Blazor.Diagrams#39]

**Comment by zHaytam** [comment]
I mean you can customize the CSS however you want but you should just create a custom node that fits your needs.

**Comment by carlosast** [comment]
Do you have a suggestion on how to do this?

**Comment by zHaytam** [comment]
You can look at the custom node demo (https://github.com/zHaytam/Blazor.Diagrams/tree/master/samples/SharedDemo/Demos) and the sample project (https://github.com/zHaytam/Blazor.DatabaseDesigner).

**Comment by zHaytam** [comment]
I assume the question has been answered, if not, feel free to re-open!
