### ISSUE TITLE
If create node after resize the Diagram canvas, port locations are incorrect and links show incorrectly

### ISSUE THREAD

**Issue by joezearing** [zHaytam/Blazor.Diagrams#40]
Steps to reproduce:
Create an empty diagram.
Add two nodes and then connect them with a link.  The link will be shown correctly.
Resize the window.
Add a new node.  Connect the new node to an existing node.  The link will be shown incorrectly with an offset to the target port.
As you drag to connect the link, the position of the link terminal is correct.  As soon as it is connected to a port, the link end position jumps away.
Pre resize:
![image](https://user-images.githubusercontent.com/71904799/97365696-544b9300-1863-11eb-833c-2cded4216793.png)
Post resize and adding a new node:
![image](https://user-images.githubusercontent.com/71904799/97365768-72b18e80-1863-11eb-9d44-db43f4750988.png)

**Comment by zHaytam** [comment]
I can't seem to be able to reproduce this with the current demos.  
Would it be possible for you to give me a simple repository where the issue shows?

**Comment by zHaytam** [comment]
I was able to reproduce it finally.
Working on a fix right now!

**Comment by zHaytam** [comment]
The bug seems to show when the canvas actually "moves", for example when the left side gets bigger and thus the canvas gets smaller, especially when you use something like Bootstrap's columns.

Can you confirm that is is exactly what happens to you too?

**Comment by joezearing** [comment]
Yeah, it seems that it is sensitive to the layout method used.  When the container changes shape or position when using flex it can cause the issue.  See below example component:

```
@page "/flow-editor"
@using Blazor.Diagrams.Core.Models.Core

<div style=@ContainerStyle>
    <div style="flex: 0.25; margin: 10px;">
        <div style="margin: 5px;">
            <input type="checkbox" @onchange="@(e=>UseFlex = e.Value is bool b ? b : false)" />
            <p style="display: inline;">Check to force flex layout</p>
        </div>
        <button @onclick="@AddNode">Add Node</button>
    </div>
    <div style="flex: 1; border: 1px solid green; height:80vh;">
        <CascadingValue Name="DiagramManager" Value="DiagramManager">
            <DiagramCanvas>
                <Widgets>
                    <Navigator Width="300" Height="200" DefaultStyle="true"></Navigator>
                </Widgets>
            </DiagramCanvas>
        </CascadingValue>
    </div>    
</div>

@code {
    private bool UseFlex;
    private string ContainerStyle => UseFlex ? "display: flex; flex-direction: row;" : "";
    
    private DiagramManager DiagramManager { get; set; }

    protected override void OnInitialized()
    {
        base.OnInitialized();                
        DiagramManager = new DiagramManager(new DiagramOptions
        {
            DeleteKey = "Delete", // What key deletes the selected nodes/links
            InverseZoom = false, // Whether to inverse the direction of the zoom when using the wheel
            DefaultNodeComponent = null, // Default component for nodes
            AllowMultiSelection = true, // Whether to allow multi selection using CTRL
            Links = new DiagramLinkOptions()
        });        
    }

    public void AddNode()
    {
        var n = NewNode(200, 200);
        DiagramManager.AddNodes(n);
    }
    
    private NodeModel NewNode(double x, double y)
    {
        var node = new NodeModel(new Point(x, y));
        node.AddPort(PortAlignment.Bottom);
        node.AddPort(PortAlignment.Top);
        node.RefreshAll();
        return node;
    }
}
```

**Comment by joezearing** [comment]
Another scenario in which the issue is apparent is when the content of the node is adjusted and enlarged.  The links will continue to be attached to the original location of the port.
![image](https://user-images.githubusercontent.com/71904799/97502261-02247380-1930-11eb-8d02-26ed534d9593.png)
![image](https://user-images.githubusercontent.com/71904799/97502310-208a6f00-1930-11eb-932b-527676a9becf.png)

**Comment by zHaytam** [comment]
This is very interested, thank you!
First issue is fixed, now to the second one :smile:

**Comment by joezearing** [comment]
Excellent! Thank you so much! I really appreciate it.
