### ISSUE TITLE
Community Feedback

### ISSUE THREAD

**Issue by zHaytam** [zHaytam/Blazor.Diagrams#41]
@zHaytam => I think it is excellent that you are inspired by [react-diagrams.](https://github.com/projectstorm/react-diagrams) to create something unique for Blazor. 

What I find interesting is the idea of 
- [Architecture Question](https://projectstorm.gitbook.io/react-diagrams/about-the-project/architecture-questions) , specifically with how best to implement [model versus widget ](https://projectstorm.gitbook.io/react-diagrams/about-the-project/architecture-questions#model-vs-widget)in the context of Blazor. 
- [End to End Testing ](https://projectstorm.gitbook.io/react-diagrams/about-the-project/testing#end-to-end-testing) in the context of Model versus widget

Last

I am also curious HOW you would implement the drag and drop in the context of Blazor ( e.g. your Blazor.DatabaseDesigner) for dragging a node or link icon from a side bar menu into the canvas. 

Second Last

Perhaps there is need for community to eventually share their custom node and link as Nuget packages. 
- Perhaps we could think if **isolation CSS and javascript** specific for the custom node or link within Nuget packages

_Originally posted by @GeorgeS2019 in https://github.com/zHaytam/Blazor.Diagrams/issues/27#issuecomment-717856794_

**Comment by GeorgeS2019** [comment]
@zHaytam I think the title could be re-phrase to community feedback. :-)

**Comment by zHaytam** [comment]
Fixed title :smile:

1. This is why I like react-diagrams, everything is a model and this helps a lot in complex systems and designs.
2. The E2E tests will be added to this library but it's gonna take some time.
3. I will be adding an example of drag & drop in the demos, but they are pretty straightforward to add since they are blazor-specific and not library-specific (maybe I'll add some helper methods).
4. I think this is already possible using RCL (Razor Class Libraries)

**Comment by GeorgeS2019** [comment]
@zHaytam  thank you for speedy showing a demo for the drag and drop with your recent commit.

**Comment by zHaytam** [comment]
I'm closing this because it's not actually an issue.
Thank you again for the feedback!

**Comment by GeorgeS2019** [comment]
@zHaytam  Please see if it is possible to apply your Blazor diagram framework to this [Blazor workflow designer.](https://github.com/elsa-workflows/elsa-core/issues/362#issuecomment-727919052)

**Comment by GeorgeS2019** [comment]
@zHaytam  if u have time, please comment of the [requirements ](https://github.com/elsa-workflows/elsa-core/issues/362#issuecomment-727928026)if your framework can address that.

**Comment by sfmskywalker** [comment]
Blazor Diagrams is looking promising.

From looking at its current list of features, it should already be usable for Elsa Workflows, except probably the lack of support for free links. In Elsa, any number of source nodes (with a finite set of ports) should be connectable to a given target node (regardless of its set of ports). Ports in Elsa are source-only, and target-ports are (presumably) created on the fly (using JsPlumb).

I'll be watching this repo closely.

@GeorgeS2019 Thanks for making me aware of this project!

**Comment by GeorgeS2019** [comment]
@sfmskywalker  The .NET community needs a working open source Blazor workflow designer.

I think zHaytam is busy. 

We already discussed Port Free links between Node.

E2E testing is also part of milestones.

Thank you for being open to look into Blazor Diagram as one option.
