### ISSUE TITLE
Samples app hosted on gh-pages crashes when encountering captcha redirects

### ISSUE THREAD

**Issue by schaveyt** [zHaytam/Blazor.Diagrams#71]
The https://blazor-diagrams.zhaytam.com/ seems to have some CORS configuration corner-case issue when handling captcha redirect. My corporate network has detected these gh-pages as requiring captcha user interaction. So me other corporate users won't beable to see all the awesome work you are doing :disappointed:

Below a snippet of the console error:
![image](https://user-images.githubusercontent.com/10182644/105188812-49229f00-5b02-11eb-9c7e-16c6095491c6.png)

**Comment by zHaytam** [comment]
This is very very very weird!
I am only using GitHub Pages to host the website, don't know what could trigger this. Do other Blazor WASM websites work for you? Maybe your internal network flags requests that fetch dlls?

**Comment by schaveyt** [comment]
Good question. Let me see if I can find another gh-pages hosted blazorwasm site to check that.

**Comment by schaveyt** [comment]
By the way, just viewed the demo from my personal machine. OMG.....this is amazing. I was am not familar with react-diagrams but having support for ports out of the box is amazing!. So glad I found this..so glad you are sharing this 🥇

**Comment by schaveyt** [comment]
I was able to view this page: https://swimburger.github.io/BlazorGitHubPagesDemo/. 

My hunch is that our corporate security is happy with github.io sites but is considering your zhaytam.com as suspicious and requires user captcha confirmation.

**Comment by schaveyt** [comment]
Yup. I successfully was able to load the demo by visiting: https://zhaytam.github.io/Blazor.Diagrams

You may want to consider offering a "mirror" url to the github.io page 👍

**Comment by zHaytam** [comment]
Thank you for the kind words! I'm glad it's helpful to some people :')

That's great, I'll see where I can add that alternative url. Although I find it weird that it works since it'll only redirect you (301) to my domain, but hey it works!

**Comment by schaveyt** [comment]
Yeah, I saw that redirection too :smile:. Very glad it finally worked. Once you've had a chance to add the url.  You are free to close this issue.
