### ISSUE TITLE
Select/Unselect all

### ISSUE THREAD

**Issue by Rickybarb5** [zHaytam/Blazor.Diagrams#74]
It would be cool if there were shortcuts and methods to select and unselect all nodes, with events of course.

**Comment by zHaytam** [comment]
Hello,
There is a `UnselectAll` method but not a `SelectAll` method, maybe I don't know if it'll select everything or just nodes.

For the shortcuts, I don't think it's supposed to be available out of the box, at least I didn't see it in any other diagramming library. I believe it's up for the library users to add that, which is pretty easy to do using a `DiagramSubManager`.

Example: https://github.com/zHaytam/Blazor.Diagrams/blob/master/src/Blazor.Diagrams.Core/Default/GroupingSubManager.cs
WHich you use like this: `_diagramManager.RegisterSubManager<YourSubManager>();`.
