### ISSUE TITLE
custom css not working

### ISSUE THREAD

**Issue by BjornEngelen** [zHaytam/Blazor.Diagrams#76]
Hello,

It seems that custom css in the nodetemplate is not being applied.

Minimal example:

**FunctionNodeWidget.razor**
```
<div class="default-node functionnode @(Node.Group != null ? "grouped" : "") @(Node.Selected ? "selected" : "")" style="width: 250px; background-color: @Node.Function.Color">
    @Node.Function.Name
    @foreach (var port in Node.Ports.Cast<FunctionPortModel>())
    {
        <PortRenderer Port="port" Class="functionport">@port.Connector.Name</PortRenderer>
    }
</div>

@code {
    [Parameter]
    public FunctionNode Node { get; set; }
}
```

As you can see I'm adding class functionport on the PortRenderer. It is defined in the component's stylesheet:

**FunctionNodeWidget.razor.css**
```
.functionport {
    padding: 5px;
    margin: -18px;
    border-radius: 50%;
    background-color: #f5f5f5;
    border: 1px solid #d4d4d4;
    cursor: pointer;
    position: absolute;
}
```

It does not get applied at runtime. Moving the class to app.css doesn't work either.
Am I doing something wrong? 

Thank you

**Comment by zHaytam** [comment]
Hello, can you try the following CSS:
```
::deep .functionport {
    padding: 5px;
    margin: -18px;
    border-radius: 50%;
    background-color: #f5f5f5;
    border: 1px solid #d4d4d4;
    cursor: pointer;
    position: absolute;
}
```

Since the PortRenderer is a component, styling its parent wouldn't work unless you use `::deep`.

**Comment by BjornEngelen** [comment]
@zHaytam 

Hello, it doesn't seem to help.
I have added the resulting HTML: note that the child content of the port  (@port.connector.name) is not included as well.

```
<div class="default-node functionnode  selected" style="width: 250px; background-color: #fff0c1" b-hmg4z5k0br="">
Functionname
<!--!-->
<div class="port top  functionport" _bl_5=""></div>
<!--!-->
<div class="port bottom  functionport" _bl_6=""></div>
</div>
```

**Comment by zHaytam** [comment]
Are you sure `@port.Connector.Name` is not null or empty?
Can you post your generated CSS (from CSS isolation) as well? It should have something like `[b-hmg4z5k0br] .functionport`

**Comment by BjornEngelen** [comment]
it exists in the generated css

```
/* /Pages/Diagrams/FunctionNodeWidget.razor.rz.scp.css */
[b-hmg4z5k0br] .functionport {
    padding: 5px;
    margin: -18px;
    border-radius: 50%;
    background-color: #f5f5f5;
    border: 1px solid #d4d4d4;
    cursor: pointer;
    position: absolute;
}
```

Concerning the name, a bug in my code indeed did not fill the name correctly. That has been fixed.

**Comment by zHaytam** [comment]
So technically, the CSS is working.
If you inspect your node's ports, they aren't styled at all?

**Comment by BjornEngelen** [comment]
After some fumbling around it seems **!important** is doing the trick. I guess I'm just having some sort of precedence-issue, and there is no issue with your library. I think we can close. 

Thanks for your work and this utility
