### ISSUE TITLE
Quick start examle not working

### ISSUE THREAD

**Issue by MAKolker** [zHaytam/Blazor.Diagrams#77]
I tried to create WASM serivce using Quick Start example from documetation, but i can't make it working, diagram is not rendered (may be css issue). Please, review QuickStart code, and it would be nice if you put working example of in code repository.

**Comment by zHaytam** [comment]
![image](https://user-images.githubusercontent.com/34218324/106734706-9c711300-6613-11eb-8978-40da659743e5.png)

Did you make sure of this? The parent of `DiagramCanvas` needs to have a fixed width/height for the diagram to show, so inspect your HTML and see if the parent or the canvas don't have 0 in height or something.

There is a lot of demos in the samples, you'll also see that I specify a height in the demos:
```css
.diagram-container {
    width: 100%;
    height: calc(100% - 52px);
}
```

**Comment by MAKolker** [comment]
Oh, you a right, now it works, sorry. But may be you should include something like  
`<div style="width:700px; height: 700px">
    <CascadingValue Name="DiagramManager" Value="diagramManager">
        <DiagramCanvas></DiagramCanvas>
    </CascadingValue>
</div>`
in example. I see that my quesion is not the first one :(

**Comment by zHaytam** [comment]
I'll try to make the Quickstart easier in the future, thanks!

**Comment by inventivejon** [comment]
@MAKolker  Thank you so much for pointing this out in a clear example. I was close to giving up because it was not working at all. In my case the issue was using min-width and min-height. Seems you explicitely need to use width and height....
