### ISSUE TITLE
Number of nodes must be >= 2

### ISSUE THREAD

**Issue by joadan** [zHaytam/Blazor.Diagrams#79]
Hi,

I have a use case where I would like to add only one node to a group.
Currently that is not possible, an error is thrown: ArgumentException: Number of nodes must be >= 2.
Not sure why the limitation is there, any ideas. 

Thank you for your great work.

**Comment by zHaytam** [comment]
Hello,

I personally find that it doesn't make sense to have a group of 1 node. Even the naming (group) gives the idea that it's multiple elements. May I know why you would need a group of a single node?

Thank you

**Comment by WillianGruber** [comment]
Hi, when dragging and creating groups dynamically, maybe one group could be created with one node and later more nodes be added to this group?

**Comment by zHaytam** [comment]
> Hi, when dragging and creating groups dynamically, maybe one group could be created with one node and later more nodes be added to this group?

Hey! How do you see yourself adding that node later? Also dynamically?

**Comment by WillianGruber** [comment]
Yes, right clicking / expanding another node into a detailed view...
Are nested groups available? I'm coming back to my project now, after several months away, and things changed a lot.

**Comment by zHaytam** [comment]
Right now, nested groups are still not supported. I had 90% of the work done, but there was a problem with the order of the links, some links get displayed on top of groups, others are behind some other groups, it was a mess and I didn't find a viable solution for it.

**Comment by MichaelLant** [comment]
I also have a requirement that in certain circumstances only one node is allowed.

I also need to be able to place nodes programatically in specific locations on objects. 

As well, I need to have a directionality to nodes where a node can be either an Input Port or an Output Port. Input Ports can connect only to Output Ports. Input Ports cannot connect to Input Ports and Output Ports cannot connect to Output Ports. This is not something that I think that I see Blazor.Diagrams doing directly as there are domain rules associated with how, when and how many ports can be added or removed as well as where the Ports are located. To be more specific, I need to be able to enforce Input Port locations only on the left side of an object and Output Ports on the right side. The reason for controlling the location of the Ports by type is to create a visual workflow for processes (manufacturing, scheduling, chemical reactions, etc.).

I have not yet dug deep enough into the existing capabilities It would be terrific to have that level of control over Nodes/Ports.

I have two projects in mind where I already know all of the connection and containership rules that I need to enforce. If it would help, I can write something that describes the rules in a generic form that describes the functionality without describng the the projects. Please let me know if that would help.

Michael

**Comment by zHaytam** [comment]
Hum okay, I guess I can remove the 2 nodes minimum validation if it's really needed.
@MichaelLant I have created another issue with your questions, we can talk there.

**Comment by joadan** [comment]
Thank you @zHaytam
