### ISSUE TITLE
Adding nodes inside OnInitializedAsync causes weird port rendering.

### ISSUE THREAD

**Issue by TheAnachronism** [zHaytam/Blazor.Diagrams#83]
I was playing around with this library and tried building a diagram from information I got from an API.
So my OnInitializedAsync first creates the DiagramManager, then calls the API and then builds the nodes based on the information from that API.
That all happens inside of the OnInitializedAsync method.
But doing that causes the ports to be rendered way under the actual nodes.

Important here is, that the nodes I used are custom nodes.
But also something to mention is, if I create those nodes hard coded (so not dynamic with the API result), and do that BEFORE the API Call everything is fine.
But doing it after, so I guess after an await call, will cause this weird rendering.

Something interesting is also, that if you zoom in on the diagram, so the nodes are outside of the boundaries and then zoom out again, so you can see the nodes again, the ports get fixed.

Edit:
After some more playing around, I noticed, that if you create the nodes inside of OnAfterRender, there seems to be no problem...

**Comment by zHaytam** [comment]
Hello,

For me, this works:
```
protected override async Task OnInitializedAsync()
{
    await Task.Delay(5000);
    diagram.Nodes.Add(NewNode(500, 500));
}
```

I'm not sure exactly how you're doing, so can you please show me?  
If you can reproduce the issue and post the code here, that would be great!

**Comment by TheAnachronism** [comment]
Ok so:
First I think you meant `diagram.AddNodes(...)` because your Nodes are an IReadOnlyCollection.
Second my current OnInitializedAsync looks like this:
`

        protected override async Task OnInitializedAsync()
        {
            _itemTotals.Clear();
            if (!Guid.TryParse(RecipeIdParameter, out _currentRecipeId))
                throw new ArgumentException("Given recipe id is invalid!");

            _currentRecipe = await RecipeService.GetRecipeAsync(_currentRecipeId);
            _topRecipeTreeItem = await RecipeTreeService.CreateRecipeTreeAsync(_currentRecipe, 1);
            
            var firstNode = new RecipeNodeModel(_topRecipeTreeItem, new Point(0, 0));
            firstNode.AddPort(PortAlignment.Top);
            firstNode.AddPort();

            var secondNode = new RecipeNodeModel(_topRecipeTreeItem, new Point(0, 50));
            secondNode.AddPort(PortAlignment.Top);
            secondNode.AddPort();

            DiagramManager.AddNodes(firstNode, secondNode);
            DiagramManager.AddLink(firstNode.GetPort(PortAlignment.Bottom), secondNode.GetPort(PortAlignment.Top));

            //BuildNodeDiagram();
            //CalculateTotals();
        }
` 

I first parse some string parameter into a GUID, but thats not the problem.
The problem is the two async calls I make after that.
The two nodes I add below are just some testing nodes which are getting weirdly rendered.
RecipeNodeModel is a custom node I created but that isn't the problem either because:
If I move the creation of the nodes above my two async calls, everything works fine.
Also somehow it depends which kind of async call you make...
A simple Task.Delay doesn't cause the problem.

**Comment by zHaytam** [comment]
Yes, my bad, that's 2.0.0 lol.  
I'm sorry but I can't really reproduce it. Can't you make a simple repro for me to try and debug on? Otherwise I can't really help

**Comment by TheAnachronism** [comment]
I'll see what I can do.
I realized, that a simple API call is no problem.
So I really have to find out what about those calls are causing stuff -.-

**Comment by TheAnachronism** [comment]
Ok I finally figured it out, what the problem was.
At the start of my page I have a h2 element which has the name of an object.
That object gets requested from the API inside those two lines.
So because at the beginning that h2 element is empty and then later (but still inside OnInitializedAsync) gets filled, the port rendering is kind of bricked.

I don't exactly know why that is but a workaround for it is just setting a default value for that string inside of that h2 element.
That way it has text in it from the beginning and even if it gets updated later, it won't cause any height issues.

**Comment by zHaytam** [comment]
Ah, right! This is the same issue as https://github.com/zHaytam/Blazor.Diagrams/issues/81.
This is fixed in 2.0.0, which handles any change in the DOM and notifies the DiagramCanvas to update itself.

**Comment by TheAnachronism** [comment]
https://github.com/TheAnachronism/Blazor.Diagrams.PortRenderingHeightBug

Here I have a repo if you want to take a look at it.

**Comment by TheAnachronism** [comment]
When do you think 2.0.0 will be released?

**Comment by zHaytam** [comment]
I hope to release this month. There is already almost 50+ changes to the library. I'm currently working on the last TODO items (e.g. Orthogonal edges).

**Comment by TheAnachronism** [comment]
Nice
Anyway, thanks for the help and thanks for the awesome library!
